// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8CMrV8fJgIAdy_-FTnfKphevRHGrZQo8',
    appId: '1:443861905576:web:d9d59c318e414213ff129d',
    messagingSenderId: '443861905576',
    projectId: 'test-task-4bbfa',
    authDomain: 'test-task-4bbfa.firebaseapp.com',
    storageBucket: 'test-task-4bbfa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKbOMPVtcrY86BltsuQsf9gROUMZ2Fk6k',
    appId: '1:443861905576:android:9c45c7b9827913c8ff129d',
    messagingSenderId: '443861905576',
    projectId: 'test-task-4bbfa',
    storageBucket: 'test-task-4bbfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDutUJ6CVAIDWjECcrN2iJ6XVRgmgvzVWQ',
    appId: '1:443861905576:ios:c26de30699621b87ff129d',
    messagingSenderId: '443861905576',
    projectId: 'test-task-4bbfa',
    storageBucket: 'test-task-4bbfa.firebasestorage.app',
    iosBundleId: 'com.example.testTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDutUJ6CVAIDWjECcrN2iJ6XVRgmgvzVWQ',
    appId: '1:443861905576:ios:c26de30699621b87ff129d',
    messagingSenderId: '443861905576',
    projectId: 'test-task-4bbfa',
    storageBucket: 'test-task-4bbfa.firebasestorage.app',
    iosBundleId: 'com.example.testTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8CMrV8fJgIAdy_-FTnfKphevRHGrZQo8',
    appId: '1:443861905576:web:0026b06a736c3b1fff129d',
    messagingSenderId: '443861905576',
    projectId: 'test-task-4bbfa',
    authDomain: 'test-task-4bbfa.firebaseapp.com',
    storageBucket: 'test-task-4bbfa.firebasestorage.app',
  );
}
